"""Migration description

Revision ID: 24f2c9405807
Revises: b0a136db72bb
Create Date: 2025-07-07 02:42:42.176649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f2c9405807'
down_revision = 'b0a136db72bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 