"""Add AI features tables

Revision ID: 583c069fca2e
Revises: 8d0ef0748b87
Create Date: 2025-07-08 02:02:18.437411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583c069fca2e'
down_revision = '8d0ef0748b87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 