"""add_notifications_table

Revision ID: 8d0ef0748b87
Revises: 24f2c9405807
Create Date: 2025-07-07 11:49:42.527250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0ef0748b87'
down_revision = '24f2c9405807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 